#!/bin/bash

echo "pull lastest update...\n" \
&& git pull origin master \
&& echo "push local content to remote..." \
&& git add .deploy_git/ \
&& git add . \
&& git commit -m "`date +%F`" \
&& git push origin master \
&& echo "replace .deploy_git/.git." \
&& mv .deploy_git/git .deploy_git/.git


